task 1

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,39 +1,26 @@
 #!/usr/bin/env bash
+# Installs and sets up HAProxy
+
+# Check if the script is run as root
+if [[ $EUID -ne 0 ]]; then
+    echo "Error: This script must be run as root. Use 'sudo $0'." >&2
+    exit 1
+fi
 
 # Install HAProxy
-apt-get update
 apt-get install -y software-properties-common
-add-apt-repository -y ppa:vbernat/haproxy-2.4
+add-apt-repository -y ppa:vbernat/haproxy-1.8
 apt-get -y update
-apt-get install -y haproxy
+apt-get install -y haproxy=1.8.*
+
+# Enable HAProxy service
+echo "ENABLED=1" > /etc/default/haproxy
 
 # Configure HAProxy
 cat <<EOF > /etc/haproxy/haproxy.cfg
-global
-    log /dev/log local0
-    log /dev/log local1 notice
-    chroot /var/lib/haproxy
-    stats socket /run/haproxy/admin.sock mode 660 level admin
-    stats timeout 30s
-    user haproxy
-    group haproxy
-    daemon
-
-defaults
-    log global
-    mode http
-    option httplog
-    option dontlognull
-    timeout connect 5000
-    timeout client 50000
-    timeout server 50000
-
-frontend load_balancer
+listen load_balancer
     bind *:80
     mode http
-    default_backend web_servers
-
-backend web_servers
     balance roundrobin
     option httpclose
     option forwardfor
@@ -41,5 +28,5 @@ backend web_servers
     server 477562-web-02 34.229.69.104:80 check
 EOF
 
-# Restart HAProxy
-systemctl restart haproxy
+# Start HAProxy service
+systemctl start haproxy
